namespace: finpay

image:
  registry: docker.io/aslahea
  pullPolicy: IfNotPresent

replicaCount: 1

services:
  payment:
    name: payment-service
    tag: "1"
    # v2 image is published under a different repository/name in manifests
    v2Repository: "finpay/payment-service"
    v2Tag: "v2"
  user:
    name: user-service
    tag: "1"
  transaction:
    name: transaction-service
    tag: "1"

gateway:
  host: finpay.local

jwt:
  issuer: finpay-internal
